"use client";

import { useEffect, useMemo, useState } from "react";

type Program = { name:string; setting:string; affiliation:string; city:string; state:string; type:string; seats:number; lor:string; interviewed:number; step:number; rank:number; instagram:string; notes:string; signal:boolean };

function parseCSV(text:string){
  const rows:string[][]=[]; let row:string[]=[], cell="", q=false;
  for(let i=0;i<text.length;i++){ const c=text[i], n=text[i+1]; if(c==='"'&&q&&n==='"'){cell+='"';i++;} else if(c==='"') q=!q; else if(c===','&&!q){row.push(cell);cell="";} else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell="";} else cell+=c; }
  const out:Program[]=[]; let signal=true;
  for(const r of rows.slice(2)){ if(!r[0]&&r[13]){signal=false;continue;} if(!r[0])continue; const seatMatches=(r[5]||"").match(/-\s*(\d+)/g)||[]; out.push({name:r[0],setting:r[1],affiliation:r[2],city:r[3],state:r[4],type:r[5],seats:seatMatches.reduce((a,x)=>a+(Number(x.match(/\d+/)?.[0])||0),0),lor:r[6],interviewed:Number((r[7]||'').replace('%',''))||0,step:Number(r[8])||0,rank:Number(r[9])||999,instagram:r[10],notes:r[11],signal}); }
  return out;
}

const clamp=(n:number)=>Math.max(0,Math.min(100,n));
function score(p:Program,w:{interview:number;step:number;seats:number;rank:number},myStep:number){
  const interview=clamp(p.interviewed/30*100), fit=clamp(100-Math.max(0,p.step-myStep)*7-Math.max(0,myStep-p.step)*1.5), seats=clamp(p.seats/10*100), rank=clamp(100-(p.rank-1)/1.1);
  return Math.round((interview*w.interview+fit*w.step+seats*w.seats+rank*w.rank)/(w.interview+w.step+w.seats+w.rank));
}

export default function Home(){
 const [data,setData]=useState<Program[]>([]),[tab,setTab]=useState<'explore'|'compare'|'list'>('explore'),[signal,setSignal]=useState<'all'|'signal'|'no'>('all'),[search,setSearch]=useState(''),[myStep,setMyStep]=useState(250),[selected,setSelected]=useState<string[]>([]),[w,setW]=useState({interview:40,step:30,seats:15,rank:15});
 useEffect(()=>{fetch('/programs.csv').then(r=>r.text()).then(t=>setData(parseCSV(t)))},[]);
 const scored=useMemo(()=>data.map(p=>({...p,score:score(p,w,myStep)})).filter(p=>(signal==='all'||(signal==='signal')===p.signal)&&(`${p.name} ${p.city} ${p.state}`).toLowerCase().includes(search.toLowerCase())).sort((a,b)=>b.score-a.score),[data,w,myStep,signal,search]);
 const avg=Math.round(scored.reduce((a,p)=>a+p.interviewed,0)/(scored.length||1)*10)/10;
 const toggle=(n:string)=>setSelected(s=>s.includes(n)?s.filter(x=>x!==n):s.length<4?[...s,n]:s);
 return <main>
  <header><div><span className="eyebrow">MATCH 2027 · PM&R</span><h1>Signal Compass</h1><p>Turn a long program list into a short, explainable decision.</p></div><div className="source"><span className="pulse"/> Live-ready data source <b>{data.length} programs</b></div></header>
  <section className="controls">
   <div className="tabs">{(['explore','compare','list'] as const).map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t==='explore'?'Opportunity map':t==='compare'?`Compare (${selected.length})`:'Ranked list'}</button>)}</div>
   <div className="filters"><input aria-label="Search programs" placeholder="Search program, city, state…" value={search} onChange={e=>setSearch(e.target.value)}/><select value={signal} onChange={e=>setSignal(e.target.value as typeof signal)}><option value="all">All programs</option><option value="signal">Current signals</option><option value="no">No signal</option></select></div>
  </section>
  <section className="summary"><div><small>Programs in view</small><strong>{scored.length}</strong></div><div><small>Average interview rate</small><strong>{avg}%</strong></div><div><small>Current signal candidates</small><strong>{scored.filter(p=>p.signal).length}</strong></div><div className="step"><small>Your Step 2 · adjustable</small><input type="range" min="220" max="280" value={myStep} onChange={e=>setMyStep(+e.target.value)}/><strong>{myStep}</strong></div></section>
  <div className="disclaimer">Decision aid, not a prediction. Scores only compare the public fields in your sheet; residency outcomes depend on many unrecorded factors.</div>
  {tab==='explore'&&<><section className="workspace"><aside><h2>What should matter?</h2><p>Adjust the recipe. Every score updates instantly.</p>{([['interview','Interview rate'],['step','Step 2 fit'],['seats','Available seats'],['rank','Doximity rank']] as const).map(([k,l])=><label key={k}><span>{l}<b>{w[k]}%</b></span><input type="range" min="0" max="60" value={w[k]} onChange={e=>setW({...w,[k]:+e.target.value})}/></label>)}<button className="reset" onClick={()=>setW({interview:40,step:30,seats:15,rank:15})}>Reset weights</button><hr/><h3>How to read this</h3><p>Right = higher recorded interview rate<br/>Up = closer Step 2 fit<br/>Larger = more seats<br/>Color = composite score</p></aside><div className="chart"><div className="axis y">Closer Step 2 fit ↑</div><div className="axis x">Recorded interview rate →</div>{scored.map(p=>{const left=clamp(p.interviewed/30*88+6),top=94-clamp(100-Math.abs(p.step-myStep)*7)*.86;return <button aria-label={`${p.name}, score ${p.score}`} title={`${p.name}\n${p.interviewed}% interviewed · median ${p.step} · ${p.seats} seats`} className={`bubble ${p.signal?'isSignal':''}`} style={{left:`${left}%`,top:`${top}%`,width:32+Math.min(p.seats,12)*3,height:32+Math.min(p.seats,12)*3,background:`hsl(${p.score*1.15} 58% 45%)`}} onClick={()=>toggle(p.name)} key={p.name}>{p.name.split(' ')[0].slice(0,3)}</button>})}</div></section><h2 className="sectionTitle">Best recorded opportunities <span>Click any card to add it to Compare</span></h2><div className="cards">{scored.slice(0,6).map((p,i)=><article className={selected.includes(p.name)?'picked':''} onClick={()=>toggle(p.name)} key={p.name}><div className="cardtop"><span>#{i+1}</span><b>{p.score}</b></div><h3>{p.name}</h3><p>{p.city}, {p.state} · {p.setting}</p><div className="metrics"><span><b>{p.interviewed}%</b> interviewed</span><span><b>{p.step}</b> median Step 2</span><span><b>{p.seats||'—'}</b> seats</span></div>{p.notes&&<blockquote>{p.notes}</blockquote>}<footer><span className={p.signal?'tag sig':'tag'}>{p.signal?'SIGNAL LIST':'NO SIGNAL'}</span><button>{selected.includes(p.name)?'Added ✓':'+ Compare'}</button></footer></article>)}</div></>}
  {tab==='list'&&<section className="table"><div className="thead"><span># / Program</span><span>Interviewed</span><span>Step 2</span><span>Seats</span><span>Score</span></div>{scored.map((p,i)=><div className="tr" key={p.name}><span><b>{i+1}</b><i><strong>{p.name}</strong><small>{p.city}, {p.state} · {p.type}</small></i></span><span>{p.interviewed}%</span><span>{p.step}</span><span>{p.seats||'—'}</span><span><em>{p.score}</em><button onClick={()=>toggle(p.name)}>+</button></span></div>)}</section>}
  {tab==='compare'&&<section><h2 className="sectionTitle">Side-by-side shortlist <span>Select up to four programs from the map or list.</span></h2>{selected.length===0?<div className="empty">No programs selected yet. Return to the opportunity map and tap <b>+ Compare</b>.</div>:<div className="compare">{selected.map(n=>data.find(p=>p.name===n)!).filter(Boolean).map(p=><article key={p.name}><button className="remove" onClick={()=>toggle(p.name)}>×</button><span className={p.signal?'tag sig':'tag'}>{p.signal?'CURRENT SIGNAL':'NO SIGNAL'}</span><h2>{p.name}</h2><p>{p.city}, {p.state}</p><div className="bigscore">{score(p,w,myStep)}<small>weighted score</small></div><dl><div><dt>Interviewed</dt><dd>{p.interviewed}%</dd></div><div><dt>Median Step 2</dt><dd>{p.step}</dd></div><div><dt>Seats</dt><dd>{p.seats||'—'}</dd></div><div><dt>Doximity rank</dt><dd>#{p.rank}</dd></div><div><dt>LORs</dt><dd>{p.lor}</dd></div></dl>{p.notes&&<blockquote>{p.notes}</blockquote>}</article>)}</div>}</section>}
  <section className="sync"><div><span>↻</span><h2>Google Sheets–ready</h2><p>The app reads a plain CSV at load time. Replace <code>public/programs.csv</code> manually, or point the fetch call at a free published-Sheet CSV URL / Apps Script webhook later.</p></div><button onClick={()=>location.reload()}>Refresh data</button></section>
 </main>
}
